plugins { id 'com.android.application' }

android {
    namespace 'com.reconstruir.app'
    compileSdk 33

    defaultConfig {
        applicationId 'com.reconstruir.mobile'
        minSdk 21
        targetSdk 33
        versionCode 15
        versionName '0.15.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
